app/admin/__init__.py
# coding: utf-8

from flask import Blueprint

admin = Blueprint('admin', __name__)

from . import views

app/main.py
# coding: utf-8

from flask import Blueprint
from flask import render_template, redirect, url_for, flash, request
from models import Article, Category

main = Blueprint('main', __name__)


@main.route('/')
def index():
    article_list = Article.query.all()
    return render_template('index.html', article_list=article_list)


@main.route('/fuck')
def fuck_main():
    return 'fuck'


@main.route('/read/<article_id>', methods=['GET'])
def read(article_id):
    # a = Article.query.filter_by(id=request.args.get('id')).first()
    article = Article.query.filter_by(id=article_id).first()
    if article:
        return render_template('article.html', article=article)
    else:
        return 'Opps.', 404


@main.route('/categorys', methods=['GET'])
def categorys():
    categories = Category.query.all()
    return render_template('category_list.html', categories=categories)


@main.route('/category/<category_id>', methods=['GET'])
def category(category_id):
    category = Category.query.filter_by(id=category_id).first()
    article_list = category.articles
    return render_template('category.html', articles=article_list)

app/templates/article.html
{% extends 'base.html' %}
{% block page_content %}
<div class="col-md-8">
    <div class="act">
        <h1 class="col-md-12">{{ article.title }}</h1>
        <b class="col-md-10">--{{ article.create_time }}--</b>
        <h3 class="col-md-8">{{ article.body }}</h3>
    </div>
</div>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %} Flask-Blog {% endblock %}
{% block navbar %}

<link rel="stylesheet" href="{{ url_for('static', filename='admin/css/admin.css') }}">
<div class="navbar navbar-inverse" role="navigation"></div>
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navgation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Blog</a>
        </div>
        <div class="nav navbar-nav">
            <ul class="nav navbar-nav">
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('admin.index') }}">后台首页</a></li>
                    <li><a href="{{ url_for('admin.article') }}">文章管理</a></li>
                    <li><a href="{{ url_for('admin.category') }}">分类管理</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('admin.logout') }}">登出</a></li>
                {% else %}
                    <li><a href="{{ url_for('admin.register') }}">注册</a></li>
                    <li><a href="{{ url_for('admin.login') }}">登入</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
        {% block page_content %}
        {% endblock %}
    </div>
{% endblock %}

app/templates/category.html
{% extends 'base.html' %}
{% block page_content %}
<div class="col-md-10">
    <table class="table">
        <thead>
            <tr>
                <th class='col-md-4'>标题</th>
                <th>正文</th>
                <th class='col-md-4'>创建时间</th>
            </tr>
        </thead>
        {% for article in articles %}
        <tr>
            <td><a href="{{ url_for('main.read', article_id=article.id) }}">{{ article.title }}</a></td>
            <td>{{ article.body[:20]+'...' }}</td>
            <td>{{ article.create_time }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock%}

app/templates/category_list.html
{% extends 'base.html' %}
{% block page_content %}
<div class="col-md-6">
    <table class="table">
        <thead>
            <tr>
                <th>分类名</th>
            </tr>
        </thead>
        <tbody>
        {% for category in categories %}
            <tr>
                <td><a href="{{ url_for('main.category', category_id=category.id) }}">{{ category.name }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
        <div id="blog-app">
        <script type="text/javascript" src='../static/js/build/bundle.js'></script>
    </body>
</html>

app/templates/read.html
{% extends 'base.html' %}
{% block page_content %}
<div class="contanier">
    <div class="col-md-12">
        <h2>{{ a.title }}</h2>
        <hr>
        <p>{{ a.create_time }} | {{ a.category.name }}</p>
        {{ a.body }}
    </div>
</div>
{% endblock %}